<?php
$form = $this->form;
// echo '<pre>';
// var_dump($form);

$form->get('title')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'What needs to be done?'
]);

$form->get('completed')->setAttribute([
    'class' => 'form-control',
    'placeholder' => '',
], false);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->get('submit')->setValue('Save');
$form->prepare();

?>

<h1>Edit todo</h1>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('title')); ?>
            <?= $this->formElement($form->get('title')); ?>
            <?= $this->formElementErrors($form->get('title')); ?>                  
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('completed')); ?>
            <?= $this->formElement($form->get('completed')); ?>
            <?= $this->formElementErrors($form->get('completed')); ?>                  
        </div>
        
        <?= $this->formElement($form->get('submit')); ?>
        
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>   